### ISSUE TITLE
How to copy a directory from local machine to Bitrix24 ?

### ISSUE THREAD

**Issue by jaytxrx** [mesche/common-scripts#1]
I want to copy a directory in my local machine to Bitrix24 cloud. How can I do this ?

I see that there is a "COPY" command like the "MKCOL". But for the copy command, I didn't get info how to mention the source and destination folder.

**Comment by mesche** [comment]
Hi,
the only purpose of the script is to avoid deletion of the account due to inactivity.
For further use of the API I have no experience, sorry
