### ISSUE TITLE
bitrix 24 Multiple accounts with different username and different password not working

### ISSUE THREAD

**Issue by NaimKindradi** [mesche/common-scripts#2]
I tried to use this script for multiple accounts separated with   ;  

It works for the first account but not for the second one.
I tried following changes 

`user=('user1' 'user2') `
`password=('passFromUser1' 'passFromUser2') `

and swapped out the `${1}`  with `${i}`

`function processBitrix() {`
`	echo "Process Bitrix24 - ${i}.${domain}"`
`	local webDavURL="https://${i}.${domain}/company/personal/user/1/disk/path/${dirName}"`

Just to see what im getting

`for i in "${accountsArr[@]}"; do`
`    echo $i`
`    echo "user" ${user[i]}`
`	echo "pw" ${password[i]}`
`	echo ${basicAuth[i]}`
`    processBitrix "${i}"`
`done`

I cant get the second user or password from the array any ideas?

**Comment by mesche** [comment]
Hi, thank you for your feedback.
My previous implementation had the following idea:
Bitrix24 supports multiple (sub-)accounts within the same Bitrix24 account/credentials.
Exactly this functionality has been implemented in version 01.01.00

I have created a new version 01.02.00 of the script.
Now you can define different users/passwords for the accounts in consideration of the array index.

Hope this helps?

Best regards,
Esche
